[package]
name = "compromise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cstr = "0.2.11"
libc = "0.2.139"
once_cell = "1.17.0"
