[package]
name = "common_define"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.32"
libloading = "^0.7"
abi_stable = "0.11.1"
crc32fast = "1.3.2"